### ISSUE TITLE
Continuous Explosion

### ISSUE THREAD

**Issue by Beamer02** [7ark/Battle-Tracks-Issues#1]
On occasion, there are explosions that continue to explode for way longer than intended.  I do not have a video of this but if I get one I will send it.

**Comment by Beamer02** [comment]
This seems to happen when 2 bullets hit each other more than when a tank or mine explodes

**Comment by Beamer02** [comment]
I got an ok video of this so itll be in discord.

**Comment by 7ark** [comment]
Resolved
